# Generated by Django 6.0.1 on 2026-01-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_alter_chatmessage_user_alter_listener_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='frequency',
            field=models.DecimalField(decimal_places=1, default=101.1, help_text='Frequency (e.g., 101.1)', max_digits=4, unique=True),
            preserve_default=False,
        ),
    ]
